id: ADCBE6241
title: 'Youthfulness Gained in Vajra-like Immortality: Verses of Truth for the Long
  Life of the Perfect Masters'
type: translation
pechas:
- I951E83B5
- I4F45ED45
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:33:19.907987
  last_modified_at: 2023-01-04 11:33:19.908001
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  I951E83B5/6A63: B1C3
  I4F45ED45/2D7E: B1C3
